// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3YQaDMoC6hTCMvfALGBgiFpDWYIsvu4',
    appId: '1:799225757524:web:ec48cf74ad30e118f4d2c1',
    messagingSenderId: '799225757524',
    projectId: 'adv-mob-todo',
    authDomain: 'adv-mob-todo.firebaseapp.com',
    databaseURL: 'https://adv-mob-todo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adv-mob-todo.appspot.com',
    measurementId: 'G-N8J9YFQ908',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIATWtPi8HpBxfQ88n656nzsiC4uFbWKg',
    appId: '1:799225757524:android:393917dfc8fb2520f4d2c1',
    messagingSenderId: '799225757524',
    projectId: 'adv-mob-todo',
    databaseURL: 'https://adv-mob-todo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adv-mob-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK7H9zyKIO3WSRrxxoRGvgKX9l4Nu9aFg',
    appId: '1:799225757524:ios:e4b9d0081076c89ff4d2c1',
    messagingSenderId: '799225757524',
    projectId: 'adv-mob-todo',
    databaseURL: 'https://adv-mob-todo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adv-mob-todo.appspot.com',
    iosClientId: '799225757524-pr1ds9lhbal03ic9jpgepbg2uev4q8ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
