// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSuE8H5UrSq8u_FdylC0UOWBT7JvVnUo',
    appId: '1:705292924564:web:e1ec7ec3e3d5e24500e681',
    messagingSenderId: '705292924564',
    projectId: 'tw-todo-app',
    authDomain: 'tw-todo-app.firebaseapp.com',
    storageBucket: 'tw-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVfHLRpVSXqSq61rR_WnNuCyHseVGNM4',
    appId: '1:705292924564:android:ce09d5caf99d292f00e681',
    messagingSenderId: '705292924564',
    projectId: 'tw-todo-app',
    storageBucket: 'tw-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3tIoiQoicdcwFNVFTn3i9_Sep9IE2rk',
    appId: '1:705292924564:ios:86471474398fddb100e681',
    messagingSenderId: '705292924564',
    projectId: 'tw-todo-app',
    storageBucket: 'tw-todo-app.appspot.com',
    iosBundleId: 'com.example.week4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3tIoiQoicdcwFNVFTn3i9_Sep9IE2rk',
    appId: '1:705292924564:ios:d31dc0c731091cb800e681',
    messagingSenderId: '705292924564',
    projectId: 'tw-todo-app',
    storageBucket: 'tw-todo-app.appspot.com',
    iosBundleId: 'com.example.week4.RunnerTests',
  );
}
